# Generated by Django 4.1.7 on 2023-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='用户id')),
                ('username', models.CharField(max_length=50, verbose_name='用户名字')),
                ('question_text', models.CharField(max_length=600, verbose_name='问题')),
                ('q_timestamp', models.DateTimeField(verbose_name='问题时间')),
                ('result_text', models.TextField(verbose_name='回答')),
                ('r_timestamp', models.DateTimeField(verbose_name='相应时间')),
                ('valid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='有效性')),
            ],
        ),
    ]
